name = "SuperCharged"
author = "terminalmaid"
version = "5.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e0600ef6e2a424e00d1420c3938cdca66dfc2df97c54b82ecc9572703eda9b9"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
