name = "SuperCharged"
author = "terminalmaid"
version = "4.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85a5e078076dda6723984a1ed3b32ea34c225d14e205f36a8cddd33f0b1a1284"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
