name = "SuperCharged"
author = "terminalmaid"
version = "3.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "616f4e34d1e8103eba4fb3dfaf834a10f904fd2dbcda37b6b86dbfceb3942845"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
