name = "SuperCharged"
author = "terminalmaid"
version = "3.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d151be7a8061105264ee2f77ab2c4fe25f1d270c615e5cca2d3a8c8b6a24223"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
