name = "SuperCharged"
author = "terminalmaid"
version = "5.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6727d4cdb3e933a1fce0080602678a949ab019576f575ff8bd2dd3f73d57b5dc"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
