name = "SuperCharged"
author = "terminalmaid"
version = "5.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fcc5dfc1a513f4de4062128faa445bfb4512381f269ee08b2d5baa5602a8736"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
