name = "SuperCharged"
author = "terminalmaid"
version = "3.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfddb7133da9b82f634d91d8220eda0a794806e81b636177a63dca6ea7f7eec5"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
