name = "SuperCharged"
author = "terminalmaid"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b74e83008e6776a0f1a3b2284817d89a407edbf281b4b5ba8267655d3107df6e"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
