name = "SuperCharged"
author = "terminalmaid"
version = "5.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "848f39834d8b2073ec25e2a0dc6fa45a8776f01a5ec71c1f6985453b885ad22c"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
