name = "SuperCharged"
author = "terminalmaid"
version = "5.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b748d7650793d73e7c9cae85c5ea6d02a013988db0b4a0fb267b8c2cecbb1cdd"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
