name = "SuperCharged"
author = "terminalmaid"
version = "3.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "baddb6a5413132ddadc8ae523697a90f020fecd13463dbfc2ac30a0e3871de49"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
