name = "SuperCharged"
author = "terminalmaid"
version = "4.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9de03cfdc1ba46cac60d0534c6e6e05eb8fa3efbc41d38e33ecb4e9266c4d3e6"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
