name = "SuperCharged"
author = "terminalmaid"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91df0bc692438d35328f88839f3bbde6687a889eebc5ae84527ee4d6e1386769"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
