name = "SuperCharged"
author = "terminalmaid"
version = "4.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3d815cd83157da06c9dc93df17ba14b6063c19e33736950ad21972692ac332a"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
