name = "SuperCharged"
author = "terminalmaid"
version = "4.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "579e28788a869b98dc97f83a39d9da5db851a27dda16f731256a2b09fdaf47c0"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
