name = "SuperCharged"
author = "terminalmaid"
version = "4.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "488b8323b224b1699d5db0291812481d2a7a7485ba7609b0c4cf3039064ab984"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
