name = "SuperCharged"
author = "terminalmaid"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "027af6f821209137f2f420106c4192a8a0cf4c5630eae0caeee2a4afef5802b5"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
