name = "SuperCharged"
author = "terminalmaid"
version = "4.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8964b5577a16970feacc4802ceb5800f0b2e6de16a71108f4d495f851663a07"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
