name = "SuperCharged"
author = "terminalmaid"
version = "4.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d79510d3bcc1dbb36c16f05c5e35f3d2260bcb86fd2ae14eacf8addf87f25600"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
