name = "SuperCharged"
author = "terminalmaid"
version = "4.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19285eee8c9767b3b4cc8146e78bd7992d306597a5997429c575e815e2369926"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
