name = "SuperCharged"
author = "terminalmaid"
version = "4.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2017f6dd0e8cd28b02b40a1203e8c380be6be07573ee3a25b46a9c8701718f59"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
