name = "SuperCharged"
author = "terminalmaid"
version = "5.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93ffb9b0f0a2cd47976d46a4b385d36e4cadf2a9944ab7492634383e687d8dc2"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
