name = "SuperCharged"
author = "terminalmaid"
version = "5.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cbe38fd1652bd8bb9bbf7ff6c820b9910c34a40eedc1daf21aa3f81503055c6"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
