name = "SuperCharged"
author = "terminalmaid"
version = "5.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a67613d60809d83b546247271b0d10e672e1a37f28ff3fb2c950d28598e5ae6d"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
