name = "SuperCharged"
author = "terminalmaid"
version = "4.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e6f085af1ed89661e77ae3496678f4f26cdfa247f54c185048802adab2904cd"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
