name = "SuperCharged"
author = "terminalmaid"
version = "3.5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "298eae547edb04f73919e23a72e6441fcd503fecaf7ccbd645a9cac8e6eb0dc2"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
